controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive:
      type: diff_drive_controller/DiffDriveController
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

diff_drive:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false

arm_controller:
  ros__parameters:
    publish_rate: 50.0
    joints:
      - arm_joint1
      - arm_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
