# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - end_effector_group_controller

  end_effector_group_controller:
    type: FollowJointTrajectory
    joints:
      - left_part_joint
      - right_part_joint